"""
A library of bibles which define how a character should speak at different parts of a story
Importer to load in the library.  You can load from a json file.

TODO: Describe the scheme.
"""

from __future__ import annotations

import datetime
import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final, NamedTuple, TypeIs, get_type_hints

from _type_helpers import is_dict_str_obj, is_dict_str_str, is_list_str

logger = logging.getLogger(__name__)


class LibraryVersion:
    """
    Utility class defining different version formats.  As we add more, we will increase CURRENT.
    We will use the other versions for backwards compatibility.
    """

    INITIAL: Final[int] = 2  # Use 2 as the initial so if the version is 'True' (instead of an int) it won't match
    CURRENT: Final[int] = INITIAL
    INVALID: Final[int] = 0  # Use 0 as invalid so a failed int() will return an invalid version

    @classmethod
    def is_valid_version(cls, version: int) -> bool:
        """Returns True if the version is within the valid range."""
        return version >= cls.INITIAL and version <= cls.CURRENT


class CharacterVoice(NamedTuple):
    """
    A description of how a character sounds.
    """

    register: str = ""
    tone: str = ""
    vocabulary_notes: str = ""

    @classmethod
    def is_valid_from_json(cls, data: object) -> TypeIs[dict[str, str]]:
        """
        Returns True if data is the correct structure.
        Args:
            data: The object to typecheck.  Expected a json object.
        """
        if not is_dict_str_str(data):
            return False

        return set(data.keys()) == set(CHAR_VOICE_TUPLE_VAR_TYPES)

    @classmethod
    def from_json(cls, data: object) -> CharacterVoice | None:
        """
        Attempt to convert a json object into a character voice.
        Args:
            data: The json object to convert.
        Returns: The converted character voice or None if json is not valid.
        """
        if CharacterVoice.is_valid_from_json(data):
            new_voice = CharacterVoice(**data)
            return new_voice
        return None


CHAR_VOICE_TUPLE_VAR_TYPES = get_type_hints(CharacterVoice)


@dataclass
class CharacterSceneInfo:
    """
    Information about how the character feels/responds from a specific scene.
    These can be used to track changes to a character over the course of a story.
    """

    mood: str = ""  # Single word
    emotional_state: str = ""  # More nuanced description
    notes: str = ""  # User defined notes
    generated: bool = False  # If generated by a human or ai
    generated_at: datetime.datetime = field(default_factory=datetime.datetime.now)  # Time this was generated at
    content_hash: str = ""  # Hash of the content so we can tell if the scene has changed since this was generated

    @classmethod
    def from_json(cls, data: dict[str, object]) -> CharacterSceneInfo | None:
        """
        Attempt to convert a json object into a scene info.
        Args:
            data: The json object to convert.
        Returns: The converted scene info or None if the json is not valid.
        """
        new_scene = CharacterSceneInfo()
        for data_key, data_value in data.items():
            if data_key == "mood" and isinstance(data_value, str):
                new_scene.mood = data_value
            elif data_key == "emotional_state" and isinstance(data_value, str):
                new_scene.emotional_state = data_value
            elif data_key == "notes" and isinstance(data_value, str):
                new_scene.notes = data_value
            elif data_key == "generated" and isinstance(data_value, bool):
                new_scene.generated = data_value
            elif data_key == "generated_at" and isinstance(data_value, str):
                try:
                    new_scene.generated_at = datetime.datetime.fromisoformat(data_value)
                except ValueError as e:
                    logger.error("Invalid 'Generated At' Date/Time (%s).  Defaulted to Now. Error: %s", data_value, e)
                    new_scene.generated_at = datetime.datetime.now()
            elif data_key == "content_hash" and isinstance(data_value, str):
                new_scene.content_hash = data_value

        if not new_scene.is_valid():
            return None

        return new_scene

    def to_json(self) -> dict[str, object]:
        """
        Write out a json object from this scene info.
        Returns: The json object.
        """
        return {
            "mood": self.mood,
            "emotional_state": self.emotional_state,
            "notes": self.notes,
            "generated": self.generated,
            "generated_at": self.generated_at.isoformat(),
            "content_hash": self.content_hash,
        }

    def is_valid(self) -> bool:
        """
        Returns True if this class has all the necessary fields set to valid values.
        """
        # TODO: Work out what (if any) fields are necessary and validate those are filled in
        return True


@dataclass
class CharacterBible:
    """
    A bible defining everything about how a particular character should talk.
    """

    name: str  # Required
    summary: str = ""
    voice: CharacterVoice = field(default_factory=CharacterVoice)
    speech_patterns: list[str] = field(default_factory=list[str])
    will_do: list[str] = field(default_factory=list[str])
    wont_do: list[str] = field(default_factory=list[str])
    example_lines: list[str] = field(default_factory=list[str])
    notes: str = ""
    scene_info: dict[str, CharacterSceneInfo] = field(default_factory=dict[str, CharacterSceneInfo])

    @classmethod
    def from_json(cls, name: str, data: dict[str, object]) -> CharacterBible | None:
        """
        Attempt to convert a json object into a full bible.
        Args:
            data: The json object to convert.
        Returns: The converted bible or None if the json is not valid.
        """
        new_bible = CharacterBible(name=name)

        for data_key, data_value in data.items():
            if data_key == "summary" and isinstance(data_value, str):
                new_bible.summary = data_value
            elif data_key == "voice":
                if is_dict_str_obj(data_value):
                    new_voice_info: CharacterVoice | None = CharacterVoice.from_json(data_value)
                    if new_voice_info is not None:
                        new_bible.voice = new_voice_info
            elif data_key == "speech_patterns" and is_list_str(data_value):
                new_bible.speech_patterns = [*data_value]
            elif data_key == "will_do" and is_list_str(data_value):
                new_bible.will_do = [*data_value]
            elif data_key == "wont_do" and is_list_str(data_value):
                new_bible.wont_do = [*data_value]
            elif data_key == "example_lines" and is_list_str(data_value):
                new_bible.example_lines = [*data_value]
            elif data_key == "notes" and isinstance(data_value, str):
                new_bible.notes = data_value
            elif data_key == "scene_info" and is_dict_str_obj(data_value):
                for scene_key, scene_value in data_value.items():
                    if is_dict_str_obj(scene_value):
                        new_scene_info: CharacterSceneInfo | None = CharacterSceneInfo.from_json(scene_value)
                        if new_scene_info is not None:
                            new_bible.scene_info[scene_key] = new_scene_info

        if new_bible.is_valid():
            return new_bible
        return None

    def to_json(self) -> dict[str, object]:
        """
        Write out a json object from this bible.
        Returns: The json object.
        """
        scene_dict: dict[str, dict[str, object]] = {}
        for scene_name, scene_data in self.scene_info.items():
            scene_dict[scene_name] = scene_data.to_json()

        return {
            "summary": self.summary,
            "voice": self.voice._asdict(),
            "speech_patterns": self.speech_patterns,
            "will_do": self.will_do,
            "wont_do": self.wont_do,
            "example_lines": self.example_lines,
            "notes": self.notes,
            "scene_info": scene_dict,
        }

    def is_valid(self) -> bool:
        """
        Returns True if this class has all the necessary fields set to valid values.
        """
        # TODO: Work out what (if any) fields are necessary and validate those are filled in
        return True


@dataclass
class CharacterLibrary:
    """
    A collection of Bibles containing everything about how a collection of characters should talk.
    """

    version: int = LibraryVersion.INVALID
    language: str = ""
    bibles: dict[str, CharacterBible] = field(default_factory=dict[str, CharacterBible])

    @classmethod
    def from_json(cls, data: object) -> CharacterLibrary | None:
        """
        Attempt to convert a json object into a full library.
        Args:
            data: The json object to convert.
        Returns: The converted library or None if the json is not valid.
        """
        if not is_dict_str_obj(data):
            return None

        new_library: CharacterLibrary = CharacterLibrary()

        for data_key, data_value in data.items():
            if data_key == "version":
                if isinstance(data_value, int):
                    version_num = data_value
                elif isinstance(data_value, str):
                    try:
                        version_num = int(data_value)
                    except ValueError as e:
                        logger.error("Invalid version number (%s).  Aborting. Error: %s", data_value, e)
                        return None
                else:
                    logger.error("Invalid version number type (%s).  Aborting", type(data_value).__name__)
                    return None

                if not LibraryVersion.is_valid_version(version_num):
                    logger.error(
                        "Version number (%d) invalid.  Must be between Initial (%d) and current: (%d).  Aborting.",
                        version_num,
                        LibraryVersion.INITIAL,
                        LibraryVersion.CURRENT,
                    )
                    return None
                else:
                    new_library.version = version_num
            elif data_key == "language" and isinstance(data_value, str):
                new_library.language = data_value
            elif data_key == "bibles" and is_dict_str_obj(data_value):
                for bible_key, bible_value in data_value.items():
                    if is_dict_str_obj(bible_value):
                        new_bible: CharacterBible | None = CharacterBible.from_json(bible_key, bible_value)
                        if new_bible is not None:
                            new_library.bibles[bible_key] = new_bible

        if new_library.is_valid():
            return new_library
        return None

    def to_json(self) -> dict[str, object]:
        """
        Write out a json object from this library.
        Returns: The json object.
        """
        bibles_dict: dict[str, dict[str, object]] = {}
        for bible_name, bible_data in self.bibles.items():
            bibles_dict[bible_name] = bible_data.to_json()
        return {"version": self.version, "language": self.language, "bibles": bibles_dict}

    def is_valid(self) -> bool:
        """
        Returns True if this class has all the necessary fields set to valid values.
        """
        return LibraryVersion.is_valid_version(self.version) and self.language != "" and len(self.bibles) > 0


class BibleImporter:
    """
    Currently a stateless class that wraps all the ways to load the bible.
    """

    def load_library(self, path: Path) -> CharacterLibrary | None:
        """Loads the character library from a json file.
        Args:
            path: The location of the library to load.
        """
        try:
            with open(path, encoding="utf-8") as file:
                data = json.load(file)
                library = CharacterLibrary.from_json(data)
        except (OSError, json.JSONDecodeError) as e:
            logger.error("Failed to load bible from %s: %s", path, e)
            return None

        return library

    def save_library(self, path: Path, library: CharacterLibrary) -> bool:
        """
        Saves the character library.
        Args:
            path: The location to save the character library.
            library: The library to save.
        Returns:
            bool: Returns True if save was successful.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        try:
            with open(path, "w", encoding="utf-8") as file:
                json.dump(library.to_json(), file, indent=2, ensure_ascii=False)
                return True
        except OSError as e:
            logger.error("Failed to save bible as %s: %s", path, e)
            return False
